spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/metadata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate

logging:
  level:
    ohio:
      rizz:
        streamingservice: DEBUG

storage-service:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin