spring:
  datasource:
    user:
      url: ${POSTGRES_USER_JDBC_URL}
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    playlist:
      url: ${POSTGRES_PLAYLIST_JDBC_URL}
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    default-TTL: 15m
    type: redis
  security:
    encryption-config:
      salt-length: 16
      hash-length: 32
      parallelism: 1
      memory: 47104
      iterations: 2
    jwt:
      secret-key: ${SECRET_SIGNING_KEY}
      access-token-expiration: 1h
      refresh-token-expiration: 7d

liquibase:
  user:
    change-log: classpath:liquibase/user/changelog-master.yaml
  playlist:
    change-log: classpath:liquibase/playlist/changelog-master.yaml